### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by juanetec** [Servoy/svySFTP#1]
Hi, 
I have install the jsch-0.1.53.jar at the plugin folder, I have installed the svyUtils on my solution and I cannot find how to use it.
What I have missed?
Is this plugin that replace the it2be-ftp plugin?

Un Saludo

Juan Ramírez

**Comment by seanthomasdevlin** [comment]
Hi Juan,

This repository is very old, unsupported and should have already been archived (flagged, read-only).
Thank you for bringing it to our attention.

For S/FTP capability, I would consider https://servoycomponents.com/components/plugins (Formerly IT2Be) or [CData](https://www.cdata.com/drivers/sftp/).

Both 3rd-party products.

Best,
Sean
